import sys

limit = int(sys.argv[1])

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibs = [1, 2]
sum = 2
while fibs[-1] <= limit:
    a, b = fibs
    c = a + b
    if c % 2 == 0:
        sum += c
    fibs = [b, c]

print(sum)  # 4613732
